// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbjhnmpcvgretebnywiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiamhubXBjdmdyZXRlYm55d2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODcyODcsImV4cCI6MjA2NzU2MzI4N30.MT6v4r0xQ2jVmnP3sIi0ApxJOBdXjRzwo2_6G2ukXu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});